# Generated by Django 6.0.5 on 2026-06-18 22:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_ID', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='cafes.cafe')),
            ],
        ),
    ]
