# Generated by Django 6.0.5 on 2026-06-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('paid', 'Paid')], default='open', max_length=10),
        ),
    ]
