# Generated by Django 6.0.5 on 2026-06-16 18:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('menu_ID', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)])),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='cafes.cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Ithem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('ithem_ID', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=3, max_digits=30)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ithem', to='menu.menu')),
            ],
        ),
    ]
